### PR TITLE
Added a utility handler for Hapi

### PR DESCRIPTION
**Pull request by mrlannigan**
A simple addition to make this module even cooler... ;) comes complete with tests.

### CODE REVIEW

**Comment by TomFrost** [comment]
This looks great, thanks for the contrib! I'm on mobile now, but will merge as soon as I get to a desktop and verify the tests.

**Comment by mrlannigan** [comment]
Hi @TomFrost, any movement on this?

**Comment by TomFrost** [comment]
How's that for movement? ;-).  Sorry about the huge delay -- this totally slipped my mind.  Thanks for the reminder, and thanks again for the great addition!

**Comment by TomFrost** [comment]
Published in NPM @0.3.0

**Comment by mrlannigan** [comment]
Sweet!

Julian Lannigan
julian.lannigan@gmail.com

**Pull request merged**
